[package]
name = "madora"
version = "0.1.0"
description = "Madora desktop Markdown editor"
authors = ["refinex"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/the-manifest.html

[lib]
name = "madora_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.2", features = [] }

[dependencies]
arboard = { version = "=3.6.1", features = ["wayland-data-control"] }
base64 = "0.22"
chrono = { version = "0.4", default-features = false, features = ["std"] }
hex = "0.4"
image = { version = "=0.25.4", default-features = false, features = ["gif", "jpeg", "png", "webp"] }
keyring = { version = "3", features = ["apple-native", "windows-native", "sync-secret-service", "crypto-rust"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
toml_edit = "0.22"
sha2 = "0.10"
portable-pty = "0.9.0"
quick-xml = "=0.39.4"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
tauri = { version = "~2.11.2", features = ["protocol-asset"] }
tauri-plugin-log = "2"
tauri-plugin-dialog = "2.7.1"
tauri-plugin-fs = "2.5.1"
tauri-plugin-opener = "2.5.4"
tauri-plugin-process = "2.3.1"
tauri-plugin-shell = "2.3.5"
tauri-plugin-updater = "2.10.1"
uuid = { version = "1.18.1", features = ["v4"] }
fontdb = "0.23.0"
zip = { version = "=2.4.2", default-features = false, features = ["deflate"] }

[target.'cfg(windows)'.dependencies]
webview2-com = "0.38.2"
windows = { version = "0.61.3", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging"] }
windows-core = "0.61.2"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.4"
objc2-app-kit = { version = "0.3.2", default-features = false, features = ["std", "NSPrintInfo", "NSPrintOperation"] }
objc2-foundation = { version = "0.3.2", default-features = false, features = ["std", "NSDictionary", "NSGeometry", "NSObject", "NSString", "NSURL", "NSValue"] }
objc2-web-kit = { version = "0.3.2", default-features = false, features = ["std", "WKWebView", "objc2-app-kit"] }

[dev-dependencies]
tempfile = "3.23"
