allowBuilds:
  msgpackr-extract: true
  msw: false
  sharp: true
  tesseract.js: false
  unrs-resolver: true
overrides:
  '@excalidraw/mermaid-to-excalidraw>mermaid': 11.12.1
  '@tiptap/markdown': 3.27.3
minimumReleaseAgeExclude:
  - '@markweave/react@0.1.6 || 0.1.8 || 0.1.9 || 0.2.0 || 0.3.0 || 0.3.1 || 0.3.3 || 0.3.6 || 0.4.3 || 0.5.2 || 0.5.3 || 0.8.0'
  - markweave@0.1.6 || 0.1.8 || 0.1.9 || 0.2.0 || 0.3.0 || 0.3.1 || 0.3.3 || 0.3.6 || 0.4.3 || 0.5.2 || 0.5.3 || 0.8.0
