import assert from 'node:assert/strict';
import test from 'node:test';

import {
  EXPECTED_RELEASE_ASSET_NAMES,
  validateReleaseSnapshot,
  verifyGitHubDraftRelease,
} from './verify-release-assets.mjs';

const tag = 'v0.1.12';
const sourceSha = '0123456789abcdef0123456789abcdef01234567';

function createAsset(name, id) {
  return {
    browser_download_url: `https://github.com/Refinex-Space/markune/releases/download/${tag}/${name}`,
    id,
    name,
    size: 128,
    url: `https://api.github.com/repos/Refinex-Space/markune/releases/assets/${id}`,
  };
}

function createValidSnapshot() {
  const assets = EXPECTED_RELEASE_ASSET_NAMES.map((name, index) =>
    createAsset(name, index + 1),
  );
  const assetByName = new Map(assets.map((asset) => [asset.name, asset]));
  const signatures = {
    'Markune_aarch64.app.tar.gz.sig': 'arm-signature',
    'Markune_x64.app.tar.gz.sig': 'intel-signature',
    'Markune_x64-setup.exe.sig': 'windows-signature',
  };
  const platform = (assetName, signatureName) => ({
    signature: signatures[signatureName],
    url: assetByName.get(assetName).browser_download_url,
  });

  return {
    release: {
      body: `## Markune ${tag}\n\n本版本包含功能改进、体验优化和问题修复。`,
      draft: true,
      name: 'Markune v0.1.12',
      prerelease: false,
      tag_name: tag,
      target_commitish: sourceSha,
      assets,
    },
    latestJson: {
      version: '0.1.12',
      notes: 'release notes',
      pub_date: '2026-07-24T00:00:00.000Z',
      platforms: {
        'darwin-aarch64': platform(
          'Markune_aarch64.app.tar.gz',
          'Markune_aarch64.app.tar.gz.sig',
        ),
        'darwin-aarch64-app': platform(
          'Markune_aarch64.app.tar.gz',
          'Markune_aarch64.app.tar.gz.sig',
        ),
        'darwin-x86_64': platform(
          'Markune_x64.app.tar.gz',
          'Markune_x64.app.tar.gz.sig',
        ),
        'darwin-x86_64-app': platform(
          'Markune_x64.app.tar.gz',
          'Markune_x64.app.tar.gz.sig',
        ),
        'windows-x86_64': platform(
          'Markune_x64-setup.exe',
          'Markune_x64-setup.exe.sig',
        ),
        'windows-x86_64-nsis': platform(
          'Markune_x64-setup.exe',
          'Markune_x64-setup.exe.sig',
        ),
      },
    },
    signatureContents: signatures,
  };
}

test('accepts a complete three-target draft release', () => {
  const snapshot = createValidSnapshot();

  const result = validateReleaseSnapshot({
    ...snapshot,
    expectedSourceSha: sourceSha,
    expectedTag: tag,
  });

  assert.deepEqual(result, {
    assetCount: EXPECTED_RELEASE_ASSET_NAMES.length,
    platformCount: 6,
    version: '0.1.12',
  });
});

test('accepts exact GitHub Assets API URLs generated by tauri-action', () => {
  const snapshot = createValidSnapshot();
  const assetByName = new Map(
    snapshot.release.assets.map((asset) => [asset.name, asset]),
  );
  const updaterAssets = {
    'darwin-aarch64': 'Markune_aarch64.app.tar.gz',
    'darwin-aarch64-app': 'Markune_aarch64.app.tar.gz',
    'darwin-x86_64': 'Markune_x64.app.tar.gz',
    'darwin-x86_64-app': 'Markune_x64.app.tar.gz',
    'windows-x86_64': 'Markune_x64-setup.exe',
    'windows-x86_64-nsis': 'Markune_x64-setup.exe',
  };

  for (const [platformName, assetName] of Object.entries(updaterAssets)) {
    snapshot.latestJson.platforms[platformName].url =
      assetByName.get(assetName).url;
  }

  assert.doesNotThrow(() =>
    validateReleaseSnapshot({
      ...snapshot,
      expectedSourceSha: sourceSha,
      expectedTag: tag,
    }),
  );
});

test('rejects a GitHub Assets API URL for a different asset ID', () => {
  const snapshot = createValidSnapshot();
  snapshot.latestJson.platforms['darwin-aarch64'].url =
    'https://api.github.com/repos/Refinex-Space/markune/releases/assets/999999';

  assert.throws(
    () =>
      validateReleaseSnapshot({
        ...snapshot,
        expectedSourceSha: sourceSha,
        expectedTag: tag,
      }),
    /darwin-aarch64 URL/,
  );
});

test('rejects the macOS updater omissions seen in v0.1.11', () => {
  const snapshot = createValidSnapshot();
  snapshot.release.assets = snapshot.release.assets.filter(
    (asset) => !asset.name.includes('.app.tar.gz'),
  );
  delete snapshot.latestJson.platforms['darwin-aarch64'];
  delete snapshot.latestJson.platforms['darwin-aarch64-app'];
  delete snapshot.latestJson.platforms['darwin-x86_64'];
  delete snapshot.latestJson.platforms['darwin-x86_64-app'];

  assert.throws(
    () =>
      validateReleaseSnapshot({
        ...snapshot,
        expectedSourceSha: sourceSha,
        expectedTag: tag,
      }),
    (error) => {
      assert.match(error.message, /Markune_aarch64\.app\.tar\.gz/);
      assert.match(error.message, /darwin-aarch64/);
      assert.match(error.message, /darwin-x86_64/);
      return true;
    },
  );
});

test('rejects updater URLs or signatures that do not match release assets', () => {
  const snapshot = createValidSnapshot();
  snapshot.latestJson.platforms['darwin-aarch64'].url =
    'https://example.com/untrusted-update.tar.gz';
  snapshot.latestJson.platforms['windows-x86_64'].signature =
    'wrong-signature';

  assert.throws(
    () =>
      validateReleaseSnapshot({
        ...snapshot,
        expectedSourceSha: sourceSha,
        expectedTag: tag,
      }),
    (error) => {
      assert.match(error.message, /darwin-aarch64 URL/);
      assert.match(error.message, /windows-x86_64 signature/);
      return true;
    },
  );
});

test('rejects a published or prerelease release', () => {
  const snapshot = createValidSnapshot();
  snapshot.release.draft = false;
  snapshot.release.prerelease = true;

  assert.throws(
    () =>
      validateReleaseSnapshot({
        ...snapshot,
        expectedSourceSha: sourceSha,
        expectedTag: tag,
      }),
    (error) => {
      assert.match(error.message, /must remain a draft/);
      assert.match(error.message, /must not be a prerelease/);
      return true;
    },
  );
});

test('allows the public Markune release URL in user-visible release notes', () => {
  const snapshot = createValidSnapshot();
  snapshot.release.body = [
    `## Markune ${tag}`,
    '',
    '下载地址：https://github.com/Refinex-Space/markune/releases',
  ].join('\n');

  assert.doesNotThrow(() =>
    validateReleaseSnapshot({
      ...snapshot,
      expectedSourceSha: sourceSha,
      expectedTag: tag,
    }),
  );
});

test('uses GitHub JSON media type for release metadata and binary media type for assets', async () => {
  const snapshot = createValidSnapshot();
  const requestAcceptHeaders = [];
  const textByAssetName = {
    'latest.json': JSON.stringify(snapshot.latestJson),
    ...snapshot.signatureContents,
  };
  const assetNameByUrl = new Map(
    snapshot.release.assets.map((asset) => [asset.url, asset.name]),
  );

  const result = await verifyGitHubDraftRelease({
    expectedSourceSha: sourceSha,
    expectedTag: tag,
    token: 'test-token',
    fetchImpl: async (url, options) => {
      requestAcceptHeaders.push([url, options.headers.Accept]);
      if (url.includes('/commits/')) {
        return new Response(JSON.stringify({ sha: sourceSha }), {
          headers: { 'Content-Type': 'application/json' },
          status: 200,
        });
      }
      if (url.includes('/releases?per_page=')) {
        return new Response(JSON.stringify([snapshot.release]), {
          headers: { 'Content-Type': 'application/json' },
          status: 200,
        });
      }
      const assetName = assetNameByUrl.get(url);
      return new Response(textByAssetName[assetName] ?? '', { status: 200 });
    },
  });

  assert.equal(result.version, '0.1.12');
  assert.deepEqual(
    requestAcceptHeaders.slice(0, 2).map(([, accept]) => accept),
    Array(2).fill('application/vnd.github+json'),
  );
  assert.deepEqual(
    requestAcceptHeaders.slice(2).map(([, accept]) => accept),
    Array(4).fill('application/octet-stream'),
  );
});

test('never sends the release token to an unexpected asset URL', async () => {
  const snapshot = createValidSnapshot();
  const latestAsset = snapshot.release.assets.find(
    (asset) => asset.name === 'latest.json',
  );
  latestAsset.url = 'https://example.com/latest.json';
  let requestedUnexpectedUrl = false;

  await assert.rejects(
    verifyGitHubDraftRelease({
      expectedSourceSha: sourceSha,
      expectedTag: tag,
      token: 'test-token',
      fetchImpl: async (url) => {
        if (url.includes('/commits/')) {
          return new Response(JSON.stringify({ sha: sourceSha }), {
            status: 200,
          });
        }
        if (url.includes('/releases?per_page=')) {
          return new Response(JSON.stringify([snapshot.release]), {
            status: 200,
          });
        }
        if (url.startsWith('https://example.com/')) {
          requestedUnexpectedUrl = true;
        }
        return new Response('', { status: 200 });
      },
    }),
    /latest\.json has an unexpected API URL/,
  );
  assert.equal(requestedUnexpectedUrl, false);
});

test('rejects a release tag that does not resolve to the workflow commit', async () => {
  let releasesRequested = false;

  await assert.rejects(
    verifyGitHubDraftRelease({
      expectedSourceSha: sourceSha,
      expectedTag: tag,
      token: 'test-token',
      fetchImpl: async (url) => {
        if (url.includes('/releases?per_page=')) {
          releasesRequested = true;
        }
        return new Response(
          JSON.stringify({ sha: 'ffffffffffffffffffffffffffffffffffffffff' }),
          { status: 200 },
        );
      },
    }),
    /does not resolve to the workflow source commit/,
  );
  assert.equal(releasesRequested, false);
});
